# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-18 23:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeAgenda', models.CharField(max_length=124)),
                ('dataAgendamento', models.DateTimeField()),
                ('descricao', models.CharField(max_length=57)),
            ],
        ),
        migrations.CreateModel(
            name='Compromisso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=124)),
                ('dtInicio', models.CharField(max_length=124)),
                ('dtFim', models.CharField(max_length=124)),
            ],
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=124)),
                ('sexo', models.CharField(max_length=12)),
                ('email', models.CharField(max_length=57)),
                ('endereco', models.CharField(max_length=67)),
            ],
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeP', models.CharField(blank=True, max_length=365, null=True)),
                ('dataInicio', models.DateTimeField()),
                ('dataFim', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricaoTar', models.CharField(max_length=89)),
                ('codTarefa', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioAgenda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='AgendaPrivada',
            fields=[
                ('agenda_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='agen.Agenda')),
                ('codPrivada', models.CharField(max_length=28, null=True)),
            ],
            bases=('agen.agenda',),
        ),
        migrations.CreateModel(
            name='AgendaPublica',
            fields=[
                ('agenda_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='agen.Agenda')),
                ('codPublica', models.CharField(max_length=130)),
            ],
            bases=('agen.agenda',),
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('pessoa_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='agen.Pessoa')),
                ('login', models.CharField(blank=True, max_length=50, null=True)),
                ('senha', models.CharField(blank=True, max_length=36, null=True)),
                ('Compromisso', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Comprs', to='agen.Compromisso')),
            ],
            bases=('agen.pessoa',),
        ),
        migrations.AddField(
            model_name='usuarioagenda',
            name='agenda',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Agendas', to='agen.Agenda'),
        ),
        migrations.AddField(
            model_name='projeto',
            name='tarefas',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Tarefas', to='agen.Tarefa'),
        ),
        migrations.AddField(
            model_name='agenda',
            name='pCompromisso',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='compromissos', to='agen.Compromisso'),
        ),
        migrations.AddField(
            model_name='agenda',
            name='possuiprojeto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Projetos', to='agen.Projeto'),
        ),
        migrations.AddField(
            model_name='usuarioagenda',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Usuarios', to='agen.Usuario'),
        ),
    ]
