# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-26 00:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agen', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoAgenda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=124)),
            ],
        ),
        migrations.RemoveField(
            model_name='agendaprivada',
            name='agenda_ptr',
        ),
        migrations.RemoveField(
            model_name='agendapublica',
            name='agenda_ptr',
        ),
        migrations.RemoveField(
            model_name='projeto',
            name='tarefas',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='Compromisso',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='pessoa_ptr',
        ),
        migrations.RenameField(
            model_name='usuarioagenda',
            old_name='agenda',
            new_name='agen',
        ),
        migrations.RemoveField(
            model_name='agenda',
            name='pCompromisso',
        ),
        migrations.RemoveField(
            model_name='agenda',
            name='possuiprojeto',
        ),
        migrations.AlterField(
            model_name='usuarioagenda',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Usuarios', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='AgendaPrivada',
        ),
        migrations.DeleteModel(
            name='AgendaPublica',
        ),
        migrations.DeleteModel(
            name='Pessoa',
        ),
        migrations.DeleteModel(
            name='Projeto',
        ),
        migrations.DeleteModel(
            name='Tarefa',
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
        migrations.AddField(
            model_name='agenda',
            name='tipoagend',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='TipoAgendas', to='agen.TipoAgenda'),
        ),
    ]
