# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-26 00:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agen', '0002_auto_20170925_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compromisso',
            name='dtFim',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='compromisso',
            name='dtInicio',
            field=models.DateTimeField(),
        ),
    ]
