# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-26 00:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('agen', '0003_auto_20170925_2112'),
    ]

    operations = [
        migrations.CreateModel(
            name='Convite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricaoCompromisso', models.CharField(max_length=124)),
                ('confirmarouDeclinar', models.CharField(max_length=124)),
                ('compromisso', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Compromisses', to='agen.Compromisso')),
                ('usercom', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
