# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-14 00:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Configura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hs_entrada', models.DateField()),
                ('hs_saida', models.DateField()),
                ('hs_trab_dia', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Frequencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_registro', models.CharField(max_length=145)),
                ('horario_reg', models.DateField()),
                ('ip_maquina', models.CharField(max_length=145)),
                ('status', models.CharField(max_length=145)),
                ('chef', models.CharField(max_length=145)),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomefun', models.CharField(max_length=145)),
                ('funcao', models.CharField(max_length=145)),
                ('cpf', models.CharField(max_length=145)),
                ('cargo', models.CharField(max_length=145)),
                ('departamento', models.CharField(max_length=145)),
                ('conf', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='frequencia.Configura')),
            ],
        ),
        migrations.CreateModel(
            name='Justificativa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField(blank=True, null=True)),
                ('frequencia', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='frequencia.Frequencia')),
            ],
        ),
        migrations.CreateModel(
            name='Patrao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=145)),
                ('depart', models.CharField(max_length=145)),
            ],
        ),
    ]
