# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-14 00:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frequencia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='justificativa',
            name='chefe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='frequencia.Patrao'),
        ),
        migrations.AlterField(
            model_name='frequencia',
            name='chef',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='frequencia.Patrao'),
        ),
    ]
