# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-08 17:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArtigoCientifico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=130)),
                ('autores', models.CharField(max_length=59)),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, null=True)),
                ('eventoPrincipal', models.CharField(blank=True, max_length=200, null=True)),
                ('sigla', models.CharField(max_length=5, null=True)),
                ('dataEHoraDeInicio', models.DateTimeField()),
                ('palavrasChave', models.CharField(max_length=120, null=True)),
                ('logotipo', models.CharField(max_length=15)),
                ('cidade', models.CharField(max_length=45, null=True)),
                ('uf', models.CharField(max_length=2, null=True)),
                ('endereco', models.CharField(blank=True, max_length=45, null=True)),
                ('cep', models.CharField(max_length=12, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=124)),
                ('email', models.CharField(max_length=57)),
            ],
        ),
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('pessoa_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='event.Pessoa')),
                ('curriculo', models.CharField(blank=True, max_length=365, null=True)),
                ('artigos', models.CharField(blank=True, max_length=36, null=True)),
            ],
            bases=('event.pessoa',),
        ),
        migrations.CreateModel(
            name='EventoCientifico',
            fields=[
                ('evento_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='event.Evento')),
                ('issn', models.CharField(max_length=28, null=True)),
            ],
            bases=('event.evento',),
        ),
        migrations.CreateModel(
            name='PessoaFisica',
            fields=[
                ('pessoa_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='event.Pessoa')),
                ('cpf', models.CharField(blank=True, max_length=12, null=True)),
            ],
            bases=('event.pessoa',),
        ),
        migrations.CreateModel(
            name='PessoaJuridica',
            fields=[
                ('pessoa_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='event.Pessoa')),
                ('cnpj', models.CharField(blank=True, max_length=18, null=True)),
                ('razaoSocial', models.CharField(blank=True, max_length=80, null=True)),
            ],
            bases=('event.pessoa',),
        ),
        migrations.AddField(
            model_name='evento',
            name='realizador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Eventos', to='event.Pessoa'),
        ),
        migrations.AddField(
            model_name='artigocientifico',
            name='evento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ArtigoCientificos', to='event.EventoCientifico'),
        ),
    ]
