# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-11 22:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_auto_20170908_1516'),
    ]

    operations = [
        migrations.CreateModel(
            name='CientificoAutor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Autor', to='event.Autor')),
                ('evCientifico', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='event.EventoCientifico')),
            ],
        ),
    ]
