# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-05 17:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeEvento', models.CharField(max_length=128)),
                ('dataInicio', models.DateField()),
                ('dataFim', models.DateField()),
                ('local', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Inscricao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idEvento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Evento.Evento')),
            ],
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=128)),
                ('cpf', models.CharField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=128)),
                ('descricao', models.CharField(max_length=128)),
                ('valor', models.IntegerField()),
                ('idEvento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Evento.Evento')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='pessoa',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Evento.User'),
        ),
        migrations.AddField(
            model_name='inscricao',
            name='idPessoa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Evento.Pessoa'),
        ),
        migrations.AddField(
            model_name='inscricao',
            name='idTicket',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Evento.Ticket'),
        ),
    ]
